version: '3.1'

services:

  gorm-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myrefuge
      POSTGRES_USER: root
      POSTGRES_DB: myrefugeDb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data